apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: java-pipeline
  namespace: openshift-gitops
spec:
  destinations:
    - name: in-cluster
      namespace: java-pipeline
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - 'https://github.com/gwsantos/openshift-pipelines.git'
status: {}
