apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-pipeline-secrets
  namespace: openshift-gitops
spec:
  destination:
    namespace: java-pipeline
    server: 'https://kubernetes.default.svc'
  project: gustavo
  source:
    path: tekton/secrets
    repoURL: 'https://github.com/gwsantos/openshift-pipelines.git'
    targetRevision: java-pipeline
  syncPolicy:
    automated: {}
status: {}
