apiVersion: v1
data:
  SONAR_TOKEN: NGE4ZDE4Njk2NzVjZTYzMWNjNGI3YjczODk5YWI1Mzg2YjhjMGE3NQ==
kind: Secret
metadata:
  creationTimestamp: "2023-02-06T20:46:54Z"
  name: sonar-token
  namespace: java-pipeline
  resourceVersion: "5378448"
  uid: 9d9d125d-5268-4d2b-8711-3ad60dc68b47
type: Opaque
