apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: java-pipeline
  labels:
    app.kubernetes.io/instance: java-app
    app.kubernetes.io/name: java-app
spec:
  params:
  - default: java-app
    name: APP_NAME
    type: string
  - default: 'https://github.com/gwsantos/openshift-quickstarts.git'
    name: GIT_REPO
    type: string
  - default: master
    name: GIT_REVISION
    type: string
  - default: java-app
    name: DEPLOYMENT_NAME
    type: string
  - default: 'image-registry.openshift-image-registry.svc:5000/java-pipeline/java-app'
    name: IMAGE_NAME
    type: string
  - default: .
    name: PATH_CONTEXT
    type: string
  - default: openjdk-17-ubi8
    name: VERSION
    type: string
  - default: latest
    name: IMAGE_TAG
    type: string
  - default: quay.io/evalic/java-app
    name: QUAY_REPO_URL
    type: string
  - default: >-
        http://nexus-sonatype-nexus-service-java-pipeline.apps.ocp-661003jg2h-0awt.cloud.techzone.ibm.com/repository/maven-central/
    name: NEXUS_REPO_URL
    type: string
  tasks:
    - name: fetch-repository
      params:
      - name: url
        value: $(params.GIT_REPO)
      - name: revision
        value: $(params.GIT_REVISION)
      - name: deleteExisting
        value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
      - name: output
        workspace: workspace
    - name: sonarqube-scanner
      params:
      - name: PROJECT_VERSION
        value: '1.0'
      - name: SOURCE_TO_SCAN
        value: .
      - name: SONAR_SCANNER_IMAGE
        value: >-
            docker.io/sonarsource/sonar-scanner-cli:4.6@sha256:7a976330a8bad1beca6584c1c118e946e7a25fdc5b664d5c0a869a6577d81b4f
      runAfter:
        - s2i-java
      taskRef:
        kind: Task
        name: sonarqube-scanner
      workspaces:
        - name: source
          workspace: workspace
        - name: sonar-settings
          workspace: sonar-settings
    - name: s2i-java
      params:
        - name: VERSION
          value: latest
        - name: PATH_CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: MAVEN_CLEAR_REPO
          value: 'false'
        - name: IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/java-pipeline/java-app
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:0a86ecbdfbe86e9d225b7fe4b090a0dd6d323f8afdfdf2bd933ff223ddb53320
        - name: SKIP_PUSH
          value: 'true'
        - name: ENV_VARS
          value: []
        - name: MAVEN_MIRROR_URL
          value: $(params.NEXUS_REPO_URL)
      runAfter:
        - unit-tests
      taskRef:
        kind: ClusterTask
        name: s2i-java
      workspaces:
        - name: source
          workspace: workspace
    - name: unit-tests
      params:
        - name: MAVEN_IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/openshift/java:latest
        - name: GOALS
          value:
            - test
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: .
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: workspace
        - name: maven-settings
          workspace: workspace
  workspaces:
    - name: workspace
    - name: sonar-settings
    - name: quay-dockerconfig
      optional: true
