apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: el-pipeline
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: tb-pipeline
        - kind: ClusterTriggerBinding
          ref: github-push
      name: java-pipeline
      template:
        ref: tt-pipeline
