apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: el-pipeline
  labels:
    app: java-app
    #app.kubernetes.io/component: java-app
    #app.kubernetes.io/instance: java-app
    #app.kubernetes.io/name: java-app
    #app.kubernetes.io/part-of: Triggers
spec:
  serviceAccountName: pipeline
  triggers:
    - name: push-trigger
      bindings:
      - kind: ClusterTriggerBinding
        ref: github-push
      template:
        ref: tt-pipeline
      interceptors:
        - name: "validate GitHub payload and filter on eventType"
          ref:
            name: "github"
          params:
        - name: "eventTypes"
          value: "push"
