apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: el-pipeline
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: tb-pipeline
      name: push-trigger
      template:
        ref: tt-pipeline
