apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tb-pipeline
  annotations:
    triggers.tekton.dev/old-escape-quotes: "true"
  labels:
    app: java-app
    #app.kubernetes.io/component: java-app
    #app.kubernetes.io/instance: java-app
    #app.kubernetes.io/name: java-app
    #app.kubernetes.io/part-of: Triggers
spec:
  params:
  - name: git-revision
    value: $(body.head_commit.id)
  - name: git-repo-url
    value: $(body.repository.url)
