apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tb-pipeline
  labels:
    app.kubernetes.io/instance: java-app
spec:
  params:
  - name: git-revision
    value: $(body.head_commit.id)
  - name: git-repo-url
    value: $(body.repository.url)
  - name: content-type
    value: $(header.Content-Type)
