apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tt-pipeline
  labels:
    app.kubernetes.io/instance: java-app
spec:
  params:
    - name: git-revision
    - name: git-repo-url
    - name: content-type
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        annotations:
          pipeline.openshift.io/started-by: 'kube:admin'
        generateName: pipeline-run-
        labels:
          app.kubernetes.io/instance: java-app
          app.kubernetes.io/name: java-app
          operator.tekton.dev/operand-name: openshift-pipelines-addons
          pipeline.openshift.io/runtime: java
          pipeline.openshift.io/runtime-version: openjdk-17-ubi8
          pipeline.openshift.io/type: kubernetes
          tekton.dev/pipeline: java-pipeline
        namespace: java-pipeline
      spec:
        params:
          - default: java-app
            name: APP_NAME
            type: string
          - default: 'https://github.com/gwsantos/openshift-quickstarts.git'
            name: GIT_REPO
            type: string
          - default: master
            name: GIT_REVISION
            type: string
          - default: java-app
            name: DEPLOYMENT_NAME
            type: string
          - default: 'image-registry.openshift-image-registry.svc:5000/java-pipeline/java-app'
            name: IMAGE_NAME
            type: string
          - default: .
            name: PATH_CONTEXT
            type: string
          - default: openjdk-17-ubi8
            name: VERSION
            type: string
          - default: latest
            name: IMAGE_TAG
            type: string
          - default: quay.io/evalic/java-app
            name: QUAY_REPO_URL
            type: string
          - default: >-
                http://nexus-sonatype-nexus-service-java-pipeline.apps.ocp-661003jg2h-0awt.cloud.techzone.ibm.com/repository/maven-central/
            name: NEXUS_REPO_URL
            type: string
        pipelineRef:
          name: java-pipeline
        resources: []
        status: null
        workspaces:
          - name: workspace
            persistentVolumeClaim:
              claimName: pvc-pipeline
          - name: sonar-settings
            configmap:
              sonar-settings
          - name: quay-dockerconfig
            secret:
              secretName: quay-token
            
